### ISSUE TITLE
Trix toolbar not working at all.

### ISSUE THREAD

**Issue by A1Gard** [Te7a-Houdini/laravel-trix#33]
Hello
Thanks for developing this package.

![image](https://user-images.githubusercontent.com/9222481/81638461-893b6900-942e-11ea-9fe1-37cba953bfec.png)
I seen editor but not work.

Usage information:

```
te7a-houdini/laravel-trix 2.0.1
laravel/framework 7.10.3
```
Any error in browser console.

An investigation: 

when I comment this line everything gone fine:
`window.$ = window.jQuery = require('jquery');`

What's problem with jquery?

**Comment by kiritokatklian** [comment]
Same issue here. Toolbar buttons don't work and there are no errors in the console.

@A1Gard Have you found a fix for this issue?

**Comment by Te7a-Houdini** [comment]
@A1Gard am not sure why this problem happened with jquery 

@kiritokatklian is it happening with you also using jquery ?

**Comment by kiritokatklian** [comment]
@Te7a-Houdini Yes, it's being used through Bootstrap. In my case, commenting it out doesn't fix the issue.

**Comment by kiritokatklian** [comment]
So I was able to get it to work after commenting out [axios](https://github.com/axios/axios), which apparently was preventing Trix from adding event listeners to the `trix-toolbar` element.

I tried to investigate what's causing the issue on axios side, but unfortunately I couldn't find anything.

**Comment by kiritokatklian** [comment]
@Te7a-Houdini So I've been playing around with Trix again and found out that it doesn't work well with VueJS. I'm assuming it's because they both listen to DOM changes. When you intentionally cause an error in VueJS (so it doesn't load properly), Trix works perfectly.

To fix this issue and have both working trix.js needs to load after VueJS has loaded by adding the `defer` attribute to the trix.js script and including `@trixassets` after your app.js (or wherever VueJS is imported). PR #36  addresses this issue.

**Comment by Te7a-Houdini** [comment]
fixed in #36
